vRP-Official-Developers/dunko_vrp

- vrp/cfg/lang/es.lua
This file is a translation to spanish of the entire file.
> Add es.lua

- vrp/client/gui.lua
- vrp/gui/Menu.js
- vrp/gui/main.js
We have added mouse and scroll support for the vRP menu. We have tested it a month ago, but aren't completely sure if it works with the current build. For any bugs and support, please contact me on discord: durpz.
> Mouse click menu for vRP

- vrp/cfg/lang/dan.lua
Fixed some wrong translations.
Translated missing translations.
FiveM: Carmon - Discord: ThaNightHawk#7290
> Correct Danish translations

- vrp/cfg/lang/es.lua
> Update spanish language.

- vRP_AdvancedFuel/server.lua
This will allow for the purchase of jerryCans again
add petrolCanPrice = 20 in config.lua to set price [20 = 20.00] Set to anything you want.
> Fixed: Purchase JerryCan

- vrp/cfg/groups.lua
- vrp_basic_mission/cfg/missions.lua
- vrp_hotkeys/cfg/hotkeys.lua
-Fix Coma Perms 
-Fix Item reqs for EMS missions - .P4NDAzz
-Change userlist to HOME due to numpad+ and scrollwheel conflicts
> Multiple Fixes

- vrp/cfg/groups.lua
> Added a simple mafia.

- vrp/modules/paycheck.lua
> Paycheck for the mafia.

- vrp/cfg/garages.lua
> Added garage for Mafia.

- vrp/cfg/gunshops.lua
> Added gunshop for Mafia

- vrp/cfg/item/food.lua
> Minor Spelling Errors.

- vrp/cfg/markets.lua
Items not showing in market, spelling errors.
> Minor Spelling Errors

- vrp/modules/admin.lua
> Fucking hate those Empty Admin Calls

- vrp/modules/basic_phone.lua
No longer let noobs create empty "calls"
> Gone Empty  "service" calls

- vrp/modules/identity.lua
When you create your identity you can damage the server very well, the server can stop working and now you cannot make a name with special characters like ,./'" or something else. It will let you use just these characters: from A to Z and from a to z.
Have a nice day!
> Solve for bug about identity

- vrp/modules/basic_garage.lua
If you sell vehicle to player you can put negative value, and it gives you money
> sellvehtoplayer

- vrp_basic_mission/cfg/lang/ro.lua
> Revert "Update ro.lua"

- vrp/modules/basic_garage.lua
Revert file to original version due to code issues.
> Revert basic_garage.lua

- vrp/modules/basic_garage.lua
- vrp/modules/police.lua
- vrp_basic_menu/server.lua
The store weapons and the sell vehicle function had some bugs when you were storing them/ selling the vehicle but now I have the fix for them, fully tested!
enjoy
> Fix some bugs

- vrp/modules/basic_garage.lua
Fixing that without using vrp_showroom or vrp_lscustoms resources by sighmir
> Fixing Sell Vehicle To Player function

- server.cfg
- vrp/__resource.lua
- vrp/client/inventory.lua
- vrp/modules/inventory.lua
Didn't feel like making a external resource for this, as there is not many lines of code in it. Basically just equips a backpack to the ped if he/she has >15kg in the bag.
Don't know if it's useful or nah, but here you have it :)
https://gyazo.com/24af63f9ac6692845d2cbda2d08861ef
> Adds backback if player has >15kg.

- vrp/cfg/garages.lua
- vrp/client/base.lua
- vrp/modules/basic_garage.lua
- vrp/modules/garages.lua
- vrp/modules/item_transformer.lua
A limit for the sell vehicle to player (change it in the cfg/garages.lua)
There was a bug in the item_transformers that you could still be using it while not being even closer to it (a tricky one) and it is fixed now (not well fixed but it should work)
> Limit to the SellVehToPlayer and poor bugfix to the item_transformers

- vrp/modules/item_transformer.lua
ahhhh, little mistakes that are hard to see...
sorry, this should be the last update of the file and with the bugfix at 100%
> Update item_transformer.lua (finally)

- vrp_basic_menu/runcode/server.lua
This net event allow any client to execute server side code allowing them adding groups and much more.
> Don't allow clients to execute server side code.

- server.cfg
Removed no longer used files like blips, club_B, club_R and racetrack.
> Updated server.cfg

- vrp/modules/money.lua
Fixes the bug of money not loading :D
> Fix: Money not loading 

- vrp/gui/main.js
- vrp/modules/paycheck.lua
Fixes: 
1. Fixes paychecks from Arthur
2. Fixes the ability to crash servers by sending 200k + characters in an input box.
> Fix: Ability to crash servers (200k characters issue) & Fix paychecks.

- vrp/client/player_state.lua
- vrp/modules/police.lua
> Fix: Weapon Duplication Bug

- vrp/modules/money.lua
Just allows for items to be 0 or above.
> Fix: Payment

- vrp_mysql/MySQL.lua
Just an additional check I missed to prevent any future issues.
> tweak: check if cb exists

- vrp/base.lua
Removes the unneeded loading time on spawn.
> remove: unneeded loading time

- vrp/client/clothing.lua
Fixes clothing texture indexes used the wrong native 🤦🏼
> tweak further to clothing store

- vrp/lib/Proxy.lua
- vrp/lib/Tunnel.lua
> Revert "add: removes the need for having brackets when using the proxy/tunnel from other resources."

- vrp/rageui/menu/RageUI.lua
- Fixes RageUI menus not properly closing sometimes.
> rageui tweak

- vrp/base.lua
- vrp_mysql/MySQL.lua
- Utilizes FiveM's enhanced bans feature.
- Adds extra security against people evading bans.
Do note this requires the latest artifacts to use this feature within Dunkos.
> add: Token bans (#stopbanevading)

- README.md
> update: version log

- vrp/__resource.lua
- vrp/base.lua
- vrp/cfg/garages.lua
- vrp/client/basic_garage.lua
- vrp/client/garages.lua
- vrp/modules/basic_garage.lua
- vrp/sharedcfg/options.lua
- Includes Renting of Vehicles
- Includes whole new design for garages
- Customizable for all vehicles using the garages.cfg
> add: rageui garage update

- vrp/client/clothing.lua
- vrp/modules/basic_garage.lua
- Adds Hats, Glasses, Bracelets, Watches, Earings
- Adds clear ped prop index.
> tweak: clothing stores

- vrp/__resource.lua
- vrp/cfg/admin_menu.lua
- vrp/cfg/groups.lua
- vrp/client/adminmenu.lua
- vrp/client/enumerators.lua
- vrp/modules/admin.lua
- Introduces an admin menu to vRP that is integrated. 
- Introduces a few features eg: entity deleting gun, entity cleanups, vehicle cleanups, ped cleanups all on-demand to get rid of those pesky modders!
> add: rageui admin menu

- vrp/cfg/admin_menu.lua
- vrp/cfg/groups.lua
- vrp/client/admin.lua
- vrp/modules/admin.lua
- vrp/version.lua
- Adds TP to waypoint to rageui admin menu.
> add: tp to waypoint

- vrp/base.lua
- Adds auto-creation for renting system rather than the migration only.
> tweak: vrp query

- .gitignore
- README.md
- vrp/version.lua
- Updates vRP version based on recent updates.
> add: update vRP

- vrp/base.lua
- vrp/fxmanifest.lua
- vrp/utils/utils.lua
- vrp/version.lua
- Add structure for future util usage (optimizations)
> add: util 

- vrp/client/basic_garage.lua
- vrp/modules/player_state.lua
- vrp/sharedcfg/options.lua
- Adds option to toggle more than one vehicle 
- Adds option to toggle losing inventory items on death.
> add: configuration options

- vrp/base.lua
- vrp/fxmanifest.lua
- vrp/modules/server_commands.lua
- Adds ban 
- Adds unban 
- Adds add group 
- Adds remove group 
All can be done through the server console and only the server console.
> add: console commands

- vrp/base.lua
- vrp/cfg/admin_menu.lua
- vrp/cfg/groups.lua
- vrp/client/player_state.lua
- vrp/client/warningsystem.lua
- vrp/fxmanifest.lua
- vrp/modules/admin.lua
- vrp/modules/money.lua
- vrp/modules/warningsystem.lua
- vrp/sharedcfg/options.lua
- vrp/version.lua
- Lowers the ped delay 
- Adds warning logging system (rubbertoe98 creation) with minor edits.
> Warning System & lower load time

- vrp/modules/identity.lua
Fixes potential problems that occur when queries become slower due to the influx of players.
> add: checks for user identities

- vrp/client/lootbags.lua
- vrp/client/survival.lua
- vrp/fxmanifest.lua
- vrp/modules/sv_lootbags.lua
- vrp/sharedcfg/options.lua
- Cannot guarantee this will be bug-free but functional loot bags.
> finish: lootbags

- vrp/cfg/admin_menu.lua
In The Player Options I have Added Show Warnings
> Added Show Warnings To The Admin Menu

- vrp_discordbot/commands/help.js
Added .help as a command full tested and working in my discord server
> Create help.js To Help People With VRP Discord Bot

- vrp_discordbot/bot.js
> Displays Bots Prefix (original idea)

- vrp/base.lua
> Added "getmyid", "getmytempid" chat commands

- vrp_discordbot/bot.js
> You don't understand grammar
